const assert = require('node:assert/strict')
const path = require('node:path')

module.exports = async function checkEditing(page, { select, exportProfile, screenshots }) {
    const original = await exportProfile()
    await page.click('#viewOriginal')
    await page.check('#editPositions')
    await page.selectOption('#moveAxis', 'free')
    await page.uncheck('#snapGrid')
    const allOptions = await page.locator('#previewElement option').count()
    await page.fill('#elementSearch', 'player unit frame')
    assert.ok(await page.locator('#previewElement option').count() < allOptions / 4)
    const player = await select('Player Unit Frame')
    const selectedId = await page.inputValue('#previewElement')
    const rect = element => element.locator('rect').first().evaluate(rect => ({ x: Number(rect.getAttribute('x')), y: Number(rect.getAttribute('y')),
        width: Number(rect.getAttribute('width')), height: Number(rect.getAttribute('height')) }))
    const center = rectangle => ({ x: rectangle.x + rectangle.width / 2, y: rectangle.y + rectangle.height / 2 })
    const screenCenter = () => page.locator('#previewSvg').evaluate(svg => ({ x: svg.viewBox.baseVal.width / 2, y: svg.viewBox.baseVal.height / 2 }))
    const close = (actual, expected) => assert.ok(Math.abs(actual - expected) < .03, `${actual} must match ${expected}`)
    await page.selectOption('#focusMode', 'dim')
    assert.equal(await player.getAttribute('opacity'), '1')
    assert.ok(await page.locator('#previewSvg [data-blocked="true"]').count() > 20)
    assert.equal(await page.locator('#previewSvg [data-blocked="true"] text').first().evaluate(text => getComputedStyle(text).pointerEvents), 'none')
    await page.selectOption('#focusMode', 'only')
    assert.ok(await page.locator('#previewSvg [data-element]').count() <= 6)
    assert.ok(await page.locator('#previewSvg [data-element] title').evaluateAll(titles => titles.every(title => title.textContent.startsWith('Player Unit Frame'))))
    assert.deepEqual(await exportProfile(), original)
    await page.click('#viewOriginal')
    await page.click('#focusView')
    assert.ok(Number(await page.inputValue('#previewZoom')) > 100)
    const viewport = await page.locator('#screenScroll').boundingBox(), focused = await player.boundingBox()
    assert.ok(Math.abs(focused.x + focused.width / 2 - viewport.x - viewport.width / 2) < 4)
    assert.ok(Math.abs(focused.y + focused.height / 2 - viewport.y - viewport.height / 2) < 4)
    await page.locator('#screenScroll').screenshot({ path: path.join(screenshots, 'focused-profile.png') })
    assert.equal(await page.inputValue('#previewElement'), selectedId)
    await page.click('#fitZoom')
    const originalPlayer = await rect(player)
    await page.check('#snapGrid')
    await page.click('[data-align="centerX"]')
    close(center(await rect(player)).x, (await screenCenter()).x)
    close((await rect(player)).y, originalPlayer.y)
    await page.click('#resetPosition')
    await page.click('[data-align="mirrorX"]')
    close(center(await rect(player)).x, 2 * (await screenCenter()).x - center(originalPlayer).x)
    await page.click('[data-align="mirrorX"]')
    close((await rect(player)).x, originalPlayer.x)
    assert.deepEqual(await exportProfile(), original)
    await page.click('#viewOriginal')
    await page.uncheck('#snapGrid')
    await page.fill('#elementSearch', '')
    await select('Player Unit Frame')
    await page.click('#setReference')
    const target = await select('Target Unit Frame')
    assert.match(await page.textContent('#referenceName'), /Player Unit Frame/)
    assert.equal(await page.locator('[data-reference]').count(), 1)
    const originalTarget = await rect(target)
    const y = Number(await page.inputValue('#positionY'))
    await page.fill('#positionY', String(y + 37))
    await page.locator('#positionY').press('Tab')
    await page.click('[data-align="centerY"]')
    close(center(await rect(target)).y, center(originalPlayer).y)
    await page.click('[data-align="left"]')
    close((await rect(target)).x, originalPlayer.x)
    await page.click('#resetPosition')
    await page.click('[data-align="mirrorX"]')
    close(center(await rect(target)).x, 2 * center(originalPlayer).x - center(originalTarget).x)
    await page.click('#resetPosition')
    await page.selectOption('#moveAxis', 'x')
    assert.equal(await page.isDisabled('[data-align="centerY"]'), true)
    assert.equal(await page.isDisabled('[data-align="mirrorY"]'), true)
    await page.selectOption('#moveAxis', 'free')
    await select('Player Primary Resource')
    await page.click('#setReference')
    await select('Player Unit Frame')
    await page.click('[data-align="centerX"]')
    assert.match(await page.textContent('#alignmentNote'), /moves with this element/)
    assert.deepEqual(await exportProfile(), original)
    await page.click('#viewOriginal')
    await select('Target Unit Frame')
    assert.equal(await page.textContent('#alignmentNote'), '')
    await page.click('#setReference')
    await select('Player Unit Frame')
    await page.check('#smartGuides')
    for (const view of ['#viewOriginal', '#viewScaled']) {
        await page.click(view)
        const element = await select('Player Unit Frame')
        const reference = await page.locator('[data-reference]').evaluate(rect => ({ x: Number(rect.getAttribute('x')), width: Number(rect.getAttribute('width')) }))
        const current = await rect(element)
        await element.scrollIntoViewIfNeeded()
        const elementBox = await element.boundingBox(), svg = await page.locator('#previewSvg').boundingBox()
        const worldWidth = await page.locator('#previewSvg').evaluate(svg => svg.viewBox.baseVal.width)
        const dx = (reference.x + reference.width / 2 - center(current).x - 2) * svg.width / worldWidth
        await page.mouse.move(elementBox.x + elementBox.width / 2, elementBox.y + elementBox.height / 2)
        await page.mouse.down()
        await page.mouse.move(elementBox.x + elementBox.width / 2 + dx, elementBox.y + elementBox.height / 2, { steps: 5 })
        assert.equal(await page.locator('[data-guide="x"]').count(), 1)
        close(center(await rect(element)).x, reference.x + reference.width / 2)
        await page.mouse.up()
        assert.equal(await page.locator('[data-guide]').count(), 0)
        await page.click('#resetPosition')
    }
    assert.deepEqual(await exportProfile(), original)
    await page.click('#viewOriginal')
    await page.click('#clearReference')
    await page.selectOption('#focusMode', 'all')
    await page.uncheck('#smartGuides')
    await page.uncheck('#editPositions')
    assert.equal(await page.isDisabled('[data-align="centerX"]'), true)
    console.log('Focus and alignment checks passed with the supplied profile.')
}
