const assert = require('node:assert/strict')
const path = require('node:path')

module.exports = async function checkFonts(browser, url, screenshots) {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    try {
        await page.goto(url, { waitUntil: 'networkidle' })
        const input = await page.evaluate(() => {
            const profile = structuredClone(DemoProfiles.DelvUI)
            for (const ref of PreviewFonts.references(profile)) {
                if (ref.config.FontID?.startsWith('Default_')) ref.config.FontID = ref.config.FontID.replace('Default', ref.config.FontID === 'Default_16' ? 'Roboto' : 'Expressway')
            }
            profile.configs.push({ $type: 'DelvUI.Config.FontsConfig, DelvUI', Fonts: {
                Expressway_24: { Name: 'Expressway', Size: 24 }, Expressway_20: { Name: 'Expressway', Size: 20 },
                Expressway_14: { Name: 'Expressway', Size: 14 }, Expressway_12: { Name: 'Expressway', Size: 12 },
                Roboto_16: { Name: 'Roboto', Size: 16 }
            } })
            return ConfigCodec.encode(profile)
        })
        await page.fill('#inputStr', input)
        await page.click('#previewBtn')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.locator('#fontChecks').scrollIntoViewIfNeeded()
        assert.equal(await page.inputValue('#fontFamily'), '')
        const row = page.locator('#fontRows tr').filter({ hasText: 'Roboto_16' })
        await row.locator('button').click()
        assert.equal(await row.locator('button').getAttribute('aria-pressed'), 'true')
        assert.match(await page.textContent('#fontCompareName'), /^Roboto/)
        assert.equal(await page.textContent('#fontSourceSize'), '16 px')
        assert.equal(await page.textContent('#fontScaledSize'), '24 px')
        assert.equal(await page.textContent('#fontCheckResult'), 'Matches')
        assert.equal(await page.textContent('#fontExpected'), '16 px × 1.5 = 24 px')
        assert.equal(await page.textContent('#fontLoadStatus'), 'Browser fallback')
        await page.fill('#fontSampleText', 'Small text 123')
        assert.equal(await page.textContent('#fontSourceSample'), 'Small text 123')
        assert.equal(await page.textContent('#fontScaledSample'), 'Small text 123')
        await page.fill('#manualScale', '1.333')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.match(await page.textContent('#fontCompareName'), /^Roboto/)
        assert.equal(await page.textContent('#fontScaledSize'), '21 px')
        assert.match(await page.textContent('#fontExpected'), /16 px × 1.333 ≈ 21.33 px · rounded to 21$/)
        await page.fill('#manualScale', '1.5')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.selectOption('#fontFamily', 'Expressway')
        assert.ok(await page.locator('#fontRows tr').count() > 0)
        assert.ok((await page.locator('#fontRows').textContent()).includes('Expressway'))
        assert.ok(!(await page.locator('#fontRows').textContent()).includes('Roboto'))
        assert.match(await page.textContent('#fontCompareName'), /^Expressway/)
        await page.check('#fontIssuesOnly')
        assert.equal(await page.locator('#fontCompare').isVisible(), false)
        assert.equal(await page.textContent('#fontEmpty'), 'No fonts need review.')
        await page.uncheck('#fontIssuesOnly')
        await page.selectOption('#fontFamily', 'Roboto')
        await page.click('#processBtn')
        await page.waitForFunction(() => /Ready/.test(document.getElementById('outputStatus').textContent) || document.getElementById('outputStatus').classList.contains('error'))
        const before = await page.evaluate(() => ConfigCodec.decode(document.getElementById('outputStr').value))
        if (process.env.TEST_FONT) {
            await page.setInputFiles('#fontFile', process.env.TEST_FONT)
            await page.waitForFunction(() => document.getElementById('fontLoadStatus').textContent.includes('.ttf'))
            assert.ok((await page.locator('#fontSourceSample').evaluate(element => element.style.fontFamily)).includes('PreviewFont'))
            await page.selectOption('#fontFamily', 'Expressway')
            assert.equal(await page.textContent('#fontLoadStatus'), 'Browser fallback')
            await page.selectOption('#fontFamily', 'Roboto')
            assert.ok((await page.textContent('#fontLoadStatus')).includes('.ttf'))
            await page.setInputFiles('#fontFile', { name: 'broken.ttf', mimeType: 'font/ttf', buffer: Buffer.from('broken font') })
            await page.waitForFunction(() => document.getElementById('fontLoadStatus').textContent.startsWith('Could not load that font.'))
            assert.ok((await page.textContent('#fontLoadStatus')).includes('.ttf'), 'Failed replacement keeps the previous font')
            await page.click('#clearFont')
            assert.equal(await page.textContent('#fontLoadStatus'), 'Browser fallback')
            assert.equal(await page.locator('#clearFont').isVisible(), false)
        }
        await page.click('#processBtn')
        await page.waitForFunction(() => /Ready/.test(document.getElementById('outputStatus').textContent) || document.getElementById('outputStatus').classList.contains('error'))
        assert.deepEqual(await page.evaluate(() => ConfigCodec.decode(document.getElementById('outputStr').value)), before)
        await page.fill('#manualScale', '')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.locator('#fontCompare').isVisible(), false)
        assert.equal(await page.textContent('#fontEmpty'), 'Enter a positive multiplier.')
        await page.fill('#manualScale', '1.5')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.selectOption('#fontFamily', '')
        await page.locator('#fontChecks').screenshot({ path: path.join(screenshots, 'font-scaling.png') })
        await page.setViewportSize({ width: 390, height: 844 })
        await page.locator('#fontChecks').scrollIntoViewIfNeeded()
        await page.locator('#fontChecks').screenshot({ path: path.join(screenshots, 'font-scaling-mobile.png') })
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
        assert.deepEqual(errors, [])
        console.log('Font selection, comparisons, preview files and filtering checks passed.')
    } finally { await page.close() }
}
