const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const engines = require('playwright')
const { createServer } = require('../../scripts/serve.cjs')
const checkEditing = require('./editing.cjs')
const checkWorkflow = require('./workflow.cjs')
const checkFonts = require('./fonts.cjs')
const checkResolutions = require('./resolutions.cjs')
const checkMotion = require('./motion.cjs')
const checkCustomResolutions = require('./custom-resolutions.cjs')
const checkHardening = require('./hardening.cjs')
const screenshots = path.join(os.tmpdir(), 'delvuiscaler-preview-check')
fs.mkdirSync(screenshots, { recursive: true })
const server = createServer()

;(async () => {
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
    const engine = process.env.TEST_ENGINE || 'chromium'
    const browser = await engines[engine].launch({ ...(engine === 'chromium' && process.env.TEST_BROWSER ? { channel: process.env.TEST_BROWSER } : {}), headless: true })
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
        const errors = []
        page.on('pageerror', error => errors.push(error.message))
        const select = async name => {
            const id = await page.locator('#previewElement option').evaluateAll((options, name) => options.find(option => option.text === name)?.value, name)
            assert.ok(id, `Missing element: ${name}`)
            await page.selectOption('#previewElement', id)
            return page.locator(`[data-element=${JSON.stringify(id)}]`)
        }
        const exportProfile = async () => {
            await page.click('#processBtn')
            await page.waitForFunction(() => /Ready/.test(document.getElementById('outputStatus').textContent) || document.getElementById('outputStatus').classList.contains('error'))
            return page.evaluate(() => ConfigCodec.decode(document.getElementById('outputStr').value))
        }
        const drag = async (element, dx, dy) => {
            await element.scrollIntoViewIfNeeded()
            const box = await element.boundingBox()
            const svg = await page.locator('#previewSvg').boundingBox()
            const width = await page.locator('#previewSvg').evaluate(svg => svg.viewBox.baseVal.width)
            await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
            await page.mouse.down()
            await page.mouse.move(box.x + box.width / 2 + dx, box.y + box.height / 2 + dy, { steps: 5 })
            await page.mouse.up()
            return dx * width / svg.width
        }
        await page.goto(`http://127.0.0.1:${server.address().port}`, { waitUntil: 'networkidle' })
        assert.equal(await page.evaluate(() => typeof pako), 'object')
        await page.uncheck('#smartGuides')
        await page.click('#demoUI')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        assert.ok(await page.locator('[data-kind="bar"]').count() >= 19)
        assert.equal(await page.locator('[data-kind="icon"]').count(), 8)
        let player = await select('Player Unit Frame')
        const originalInput = await page.inputValue('#inputStr')
        await drag(player, 12, 8)
        assert.equal(await page.inputValue('#positionX'), '-360')
        assert.equal(await page.isDisabled('#resetAllPositions'), true)
        await page.check('#editPositions')
        player = await select('Player Unit Frame')
        const delta = await drag(player, 20, 10)
        assert.ok(Math.abs(Number(await page.inputValue('#positionX')) - (-360 + delta)) < .1)
        assert.ok(Number(await page.inputValue('#positionY')) > 330)
        assert.ok((await exportProfile()).configs[0].Position.X > -540)
        assert.equal(await page.inputValue('#inputStr'), originalInput)
        await page.click('#viewOriginal')
        await page.click('#resetPosition')
        assert.equal(await page.inputValue('#outputStr'), '')
        assert.equal(await page.inputValue('#positionX'), '-360')
        assert.equal(await page.inputValue('#positionY'), '330')
        await page.selectOption('#moveAxis', 'x')
        assert.equal(await page.isDisabled('#positionY'), true)
        await drag(await select('Player Unit Frame'), 20, 20)
        assert.equal(await page.inputValue('#positionY'), '330')
        await page.click('#resetPosition')
        await page.selectOption('#moveAxis', 'y')
        assert.equal(await page.isDisabled('#positionX'), true)
        await drag(await select('Player Unit Frame'), 20, 12)
        assert.equal(await page.inputValue('#positionX'), '-360')
        assert.ok(Number(await page.inputValue('#positionY')) > 330)
        await page.click('#resetAllPositions')
        await page.selectOption('#moveAxis', 'free')
        await page.locator('#screenScroll').scrollIntoViewIfNeeded()
        const viewport = await page.locator('#screenScroll').boundingBox()
        const cursor = { x: viewport.x + viewport.width * .45, y: viewport.y + viewport.height * .45 }
        const framePoint = () => page.locator('#screenFrame').evaluate((frame, cursor) => {
            const rect = frame.getBoundingClientRect()
            return { x: (cursor.x - rect.left) / rect.width, y: (cursor.y - rect.top) / rect.height }
        }, cursor)
        const beforeZoom = await framePoint()
        await page.mouse.move(cursor.x, cursor.y)
        await page.mouse.wheel(0, -500)
        await page.waitForFunction(() => Number(document.getElementById('previewZoom').value) > 100)
        const afterZoom = await framePoint()
        assert.ok(Math.abs(beforeZoom.x - afterZoom.x) < .005)
        assert.ok(Math.abs(beforeZoom.y - afterZoom.y) < .005)
        const zoomedDelta = await drag(await select('Player Unit Frame'), 12, 5)
        assert.ok(Math.abs(Number(await page.inputValue('#positionX')) - (-360 + zoomedDelta)) < .1)
        await page.click('#resetAllPositions')
        await page.click('#fitZoom')
        assert.equal(await page.inputValue('#previewZoom'), '100')
        await select('Player Unit Frame')
        await page.click('#viewScaled')
        const scaledDelta = await drag(await select('Player Unit Frame'), 12, 5)
        assert.ok(Math.abs(Number(await page.inputValue('#positionX')) - (-540 + scaledDelta)) < .1)
        await page.click('#resetAllPositions')
        await page.fill('#positionX', '-450')
        await page.locator('#positionX').press('Tab')
        assert.equal((await exportProfile()).configs[0].Position.X, -450)
        await page.click('#viewOriginal')
        assert.equal(await page.inputValue('#positionX'), '-300')
        await page.click('#resetAllPositions')
        await page.selectOption('#previewJob', 'WhiteMageConfig')
        assert.match(await page.locator('#previewElement').textContent(), /White Mage/)
        const exportedBeforeDummy = await exportProfile()
        const exportString = await page.inputValue('#outputStr')
        await page.fill('#dummyName', 'River Song')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.match(await page.locator('#previewSvg').textContent(), /River Song/)
        await page.fill('#dummyStatusCount', '3')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.locator('[data-kind="icon"]').count(), 3)
        await page.uncheck('#showStatuses')
        assert.equal(await page.locator('[data-kind="icon"]').count(), 0)
        await page.fill('#dummyPartyCount', '4')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.locator('#previewElement option').evaluateAll(options => options.filter(o => /^Party Frames \/ member \d+$/.test(o.text)).length), 4)
        assert.equal(await page.inputValue('#outputStr'), exportString)
        assert.deepEqual(await exportProfile(), exportedBeforeDummy)
        await page.check('#showStatuses')
        await page.fill('#dummyStatusCount', '8')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.fill('#dummyPartyCount', '8')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.click('#viewOriginal')
        await page.screenshot({ path: path.join(screenshots, 'delvui-desktop.png'), fullPage: true })
        const precisionProfile = await page.evaluate(() => {
            const profile = structuredClone(DemoProfiles.DelvUI)
            profile.configs[0].Position.Y = 123
            return ConfigCodec.encode(profile)
        })
        await page.fill('#inputStr', precisionProfile)
        await page.click('#previewBtn')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.fill('#manualScale', '.563')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.click('#viewScaled')
        await select('Player Unit Frame')
        await page.fill('#positionX', '-100')
        await page.locator('#positionX').press('Tab')
        await page.click('#viewOriginal')
        assert.equal(await page.inputValue('#positionY'), '123')
        await page.fill('#manualScale', '1')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal((await exportProfile()).configs[0].Position.Y, 123)
        await page.fill('#manualScale', '0')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.match(await page.textContent('#previewSummary'), /positive multiplier/)
        await page.click('#processBtn')
        await page.waitForFunction(() => /Ready/.test(document.getElementById('outputStatus').textContent) || document.getElementById('outputStatus').classList.contains('error'))
        assert.match(await page.textContent('#outputStatus'), /greater than zero/)
        await page.fill('#manualScale', '1.5')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.click('#demoCD')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.click('#viewOriginal')
        assert.equal(await page.locator('[data-kind="icon"]').count(), 6)
        await page.selectOption('#previewStyle', '0')
        await select('Delv CD / Cooldown row / Rampart')
        await page.fill('#positionX', '12')
        await page.locator('#positionX').press('Tab')
        const conditional = await exportProfile()
        const rampart = conditional.configs[0].ElementList.UIElements[0].ElementList.UIElements[0]
        assert.equal(rampart.StyleConditions.Conditions[0].Style.Position.X, 18)
        assert.equal(rampart.IconStyleConfig.Position.X, 0)
        await page.click('#viewOriginal')
        await select('Delv CD / Cooldown row (group)')
        await page.fill('#positionX', '-100')
        await page.locator('#positionX').press('Tab')
        assert.match(await page.textContent('#positionNote'), /group and its children/)
        const cd = await exportProfile()
        assert.equal(cd.configs[0].ElementList.UIElements[0].GroupConfig.Position.X, -150)
        assert.equal(cd.configs[0].ElementList.UIElements[0].GroupConfig.DynamicOffset.X, 90)
        assert.equal((await page.inputValue('#outputStr')).includes('|'), false)
        await page.click('#resetAllPositions')
        await page.check('#showDisabled')
        assert.equal(await page.locator('[data-kind="icon"]').count(), 7)
        await page.click('#viewOriginal')
        await select('Delv CD / Cooldown row (group)')
        await page.selectOption('#focusMode', 'only')
        assert.equal(await page.locator('[data-kind="icon"]').count(), 6)
        assert.equal(await page.locator('[data-element][data-kind="group"]').count(), 1)
        await drag(await select('Delv CD / Cooldown row (group)'), 12, 4)
        assert.notEqual(await page.inputValue('#positionX'), '-176')
        await page.click('#resetAllPositions')
        await page.selectOption('#focusMode', 'all')
        await page.screenshot({ path: path.join(screenshots, 'delvcd-desktop.png'), fullPage: true })
        await page.fill('#inputStr', 'not a profile')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('error'))
        assert.equal(await page.inputValue('#outputStr'), '')
        assert.equal(await page.locator('[data-element]').count(), 0)
        const automaticProfile = await page.evaluate(() => ConfigCodec.encode({ kind: 'DelvCD', configs: [{
            $type: 'DelvCD.UIElements.Icon', Name: 'Automatic cooldown',
            IconStyleConfig: { Position: { X: 0, Y: 0 }, Size: { X: 40, Y: 40 } },
            TriggerConfig: { TriggerOptions: [{ $type: 'DelvCD.Triggers.CooldownTrigger', Cooldown: true, CooldownOp: 3, CooldownValue: 10 }] },
            StyleConditions: { Conditions: [{ Source: 0, Op: 3, Value: 10, Style: { Position: { X: 5, Y: 0 }, Size: { X: 60, Y: 60 } } }] }
        }] }))
        await page.fill('#inputStr', automaticProfile)
        await page.click('#previewBtn')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.click('#viewOriginal')
        await page.uncheck('#showDisabled')
        await page.selectOption('#dummyState', 'combat')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.selectOption('#previewStyle', '-2')
        const automatic = await select('Automatic cooldown')
        assert.equal(await automatic.getAttribute('data-kind'), 'icon')
        assert.equal(await page.inputValue('#positionX'), '5')
        await page.fill('#dummyCooldown', '5')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.locator('[data-kind="icon"]').count(), 0)
        await page.selectOption('#dummyState', 'layout')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.fill('#dummyCooldown', '12')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.check('#showDisabled')
        if (process.env.DELVUI_SAMPLE) {
            await page.fill('#inputStr', fs.readFileSync(process.env.DELVUI_SAMPLE, 'utf8'))
            await page.click('#previewBtn')
            await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
            const sections = await page.evaluate(() => ConfigCodec.decode(document.getElementById('inputStr').value).configs.length)
            assert.equal((await exportProfile()).configs.length, sections)
            console.log(`Profile fixture: all ${sections} sections preserved. ${await page.textContent('#previewSummary')}`)
            await page.click('#viewOriginal')
            assert.equal(await page.locator('#coverageNotes').isVisible(), false)
            assert.ok(await page.locator('#previewElement option').evaluateAll(options => options.some(option => option.text.startsWith('Enemy Nameplate'))))
            assert.ok(await page.locator('#previewElement option').evaluateAll(options => options.some(option => option.text.startsWith('Party Cooldowns'))))
            await page.uncheck('#showDisabled')
            assert.match(await page.textContent('#fontRows'), /Expressway_16/)
            const expressway = page.locator('#fontRows tr').filter({ hasText: 'Expressway_16' })
            assert.deepEqual(await expressway.locator('td').allTextContents(), ['Expressway_16', '16', '24', await expressway.locator('td').nth(3).textContent(), 'Matches'])
            await expressway.locator('button').click()
            assert.equal(await page.locator('#fontSourceSample').evaluate(element => element.style.fontSize), '16px')
            assert.equal(await page.locator('#fontScaledSample').evaluate(element => element.style.fontSize), '24px')
            await page.fill('#manualScale', '.563')
            await page.evaluate(() => new Promise(requestAnimationFrame))
            assert.equal(await page.locator('#fontRows tr').filter({ hasText: 'Expressway_16' }).locator('td').nth(2).textContent(), '9')
            await page.fill('#manualScale', '1.5')
            await page.evaluate(() => new Promise(requestAnimationFrame))
            await page.selectOption('#previewJob', 'WhiteMageConfig')
            await page.selectOption('#dummyPartyState', 'raise')
            await page.evaluate(() => new Promise(requestAnimationFrame))
            assert.ok(await page.locator('#previewElement option').evaluateAll(options => options.some(option => option.text.endsWith('/ raise / duration'))))
            await page.selectOption('#dummyPartyState', 'invuln')
            await page.evaluate(() => new Promise(requestAnimationFrame))
            assert.ok(await page.locator('#previewElement option').evaluateAll(options => options.some(option => option.text.endsWith('/ invuln / duration'))))
            await page.selectOption('#dummyPartyState', 'normal')
            await page.evaluate(() => new Promise(requestAnimationFrame))
            if (process.env.TEST_FONT) {
                const beforeFont = await exportProfile()
                await page.selectOption('#fontFamily', 'Expressway')
                await page.locator('#fontFile').setInputFiles(process.env.TEST_FONT)
                await page.waitForFunction(() => document.getElementById('fontLoadStatus').textContent.includes('.ttf'))
                assert.ok(await page.locator('#previewSvg [data-kind="text"] text').evaluateAll(elements => elements.some(element => element.getAttribute('font-family').includes('PreviewFont'))))
                assert.deepEqual(await exportProfile(), beforeFont)
                await page.click('#viewOriginal')
            }
            await page.screenshot({ path: path.join(screenshots, 'upstream-default.png'), fullPage: true })
            await checkEditing(page, { select, exportProfile, screenshots })
        }
        await page.click('#demoUI')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        const beforeGrid = await exportProfile()
        await page.check('#editPositions')
        const gridExport = await page.inputValue('#outputStr')
        await page.click('#viewOriginal')
        await page.fill('#gridX', '26')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.fill('#gridY', '34')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.fill('#gridX', '0')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.locator('#gridX').press('Tab')
        assert.equal(await page.inputValue('#gridX'), '20')
        await page.fill('#gridX', '26')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.locator('#grid').getAttribute('width'), '26')
        assert.equal(await page.locator('#grid').getAttribute('height'), '34')
        assert.equal(await page.inputValue('#outputStr'), gridExport)
        await select('Player Unit Frame')
        const assertAligned = async (element, axis = 'free') => {
            const corner = await element.evaluate(group => {
                const marker = group.getAttribute('data-kind') === 'group' && group.querySelector('circle')
                const rect = group.querySelector('rect')
                return { x: Number((marker || rect).getAttribute(marker ? 'cx' : 'x')), y: Number((marker || rect).getAttribute(marker ? 'cy' : 'y')) }
            })
            const box = await page.locator('#previewSvg').evaluate(svg => ({ x: svg.viewBox.baseVal.width / 2, y: svg.viewBox.baseVal.height / 2 }))
            for (const [key, spacing] of [['x', 26], ['y', 34]]) {
                if (axis !== 'free' && axis !== key) continue
                const units = (corner[key] - box[key]) / spacing
                assert.ok(Math.abs(units - Math.round(units)) < .001, `${key} corner must match the visible grid`)
            }
        }
        await page.click('#snapSelected')
        await assertAligned(await select('Player Unit Frame'))
        await page.click('#resetAllPositions')
        await page.check('#snapGrid')
        await drag(await select('Player Unit Frame'), 12, 11)
        await assertAligned(await select('Player Unit Frame'))
        await page.click('#resetAllPositions')
        await page.selectOption('#moveAxis', 'x')
        await drag(await select('Player Unit Frame'), 12, 11)
        await assertAligned(await select('Player Unit Frame'), 'x')
        assert.equal(await page.inputValue('#positionY'), '330')
        await page.click('#resetAllPositions')
        await page.selectOption('#moveAxis', 'free')
        await page.fill('#positionX', '-341')
        await page.locator('#positionX').press('Tab')
        await assertAligned(await select('Player Unit Frame'), 'x')
        assert.equal(await page.inputValue('#positionY'), '330')
        await page.click('#resetAllPositions')
        await page.click('#viewScaled')
        await drag(await select('Player Unit Frame'), 13, 9)
        await assertAligned(await select('Player Unit Frame'))
        await page.click('#resetAllPositions')
        assert.deepEqual(await exportProfile(), beforeGrid)
        await page.click('#demoCD')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.click('#viewOriginal')
        await page.selectOption('#previewStyle', '-1')
        await select('Delv CD / Cooldown row / Rampart')
        await page.click('#snapSelected')
        await assertAligned(await select('Delv CD / Cooldown row / Rampart'))
        const snappedCD = await exportProfile()
        assert.equal(snappedCD.configs[0].ElementList.UIElements[0].GroupConfig.Position.X, -264)
        assert.notEqual(snappedCD.configs[0].ElementList.UIElements[0].ElementList.UIElements[0].IconStyleConfig.Position.X, 0)
        const gridFixtures = await page.evaluate(() => {
            const color = { Vector: { X: 1, Y: 1, Z: 1, W: 1 } }
            const bar = { Enabled: true, Position: { X: 0, Y: 0 }, Size: { X: 100, Y: 20 }, Anchor: 4, FillColor: color }
            return [ConfigCodec.encode({ kind: 'DelvUI', configs: [{ ...bar, $type: 'DelvUI.PlayerUnitFrameConfig', Position: { X: 1, Y: 1 } }] }),
                ConfigCodec.encode({ kind: 'DelvUI', configs: [{ $type: 'DelvUI.EnemyNameplateConfig', Enabled: true, Position: { X: 0, Y: 0 },
                    BarConfig: bar, CastbarConfig: { ...bar, HealthBarAnchor: 7 } }] })]
        })
        for (const [index, input] of gridFixtures.entries()) {
            await page.fill('#inputStr', input)
            await page.click('#previewBtn')
            await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
            await page.click('#viewScaled')
            const name = index === 0 ? 'Player Unit Frame' : 'Enemy Nameplate'
            await select(name)
            await page.click('#snapSelected')
            await assertAligned(await select(name))
            if (index === 0) assert.deepEqual((await exportProfile()).configs[0].Position, { X: 0, Y: 0 })
            else {
                assert.match(await page.textContent('#positionNote'), /health or name corner/)
                assert.equal((await exportProfile()).configs[0].CastbarConfig.Position.X, 0)
            }
        }
        await page.click('#demoUI')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.click('#viewOriginal')
        await select('Player Unit Frame')
        await page.uncheck('#snapGrid')
        await page.locator('#previewZoom').evaluate(slider => { slider.value = '300'; slider.dispatchEvent(new Event('input')) })
        await page.locator('#screenScroll').scrollIntoViewIfNeeded()
        const panScroll = page.locator('#screenScroll')
        await panScroll.evaluate(scroll => { scroll.scrollLeft = (scroll.scrollWidth - scroll.clientWidth) / 2; scroll.scrollTop = (scroll.scrollHeight - scroll.clientHeight) / 2 })
        const scrollPosition = () => panScroll.evaluate(scroll => ({ x: scroll.scrollLeft, y: scroll.scrollTop }))
        const beforePan = await scrollPosition()
        const panBox = await panScroll.boundingBox()
        const panX = panBox.x + panBox.width / 2, panY = panBox.y + panBox.height / 2
        await panScroll.focus()
        await page.keyboard.down('Space')
        await page.mouse.move(panX, panY)
        await page.mouse.down()
        await page.mouse.move(panX - 40, panY - 30, { steps: 4 })
        await page.mouse.up()
        await page.keyboard.up('Space')
        const afterPan = await scrollPosition()
        assert.ok(Math.abs(afterPan.x - beforePan.x - 40) < 2)
        assert.ok(Math.abs(afterPan.y - beforePan.y - 30) < 2)
        await page.mouse.move(panX, panY)
        await page.mouse.down({ button: 'middle' })
        await page.mouse.move(panX - 30, panY - 20, { steps: 4 })
        await page.mouse.up({ button: 'middle' })
        const afterMiddlePan = await scrollPosition()
        assert.ok(Math.abs(afterMiddlePan.x - afterPan.x - 30) < 2)
        assert.ok(Math.abs(afterMiddlePan.y - afterPan.y - 20) < 2)
        assert.equal(await panScroll.evaluate(scroll => scroll.classList.contains('panning') || scroll.classList.contains('pan-ready')), false)
        assert.equal(await page.inputValue('#positionX'), '-360')
        assert.equal(await page.inputValue('#positionY'), '330')
        assert.deepEqual(await exportProfile(), beforeGrid)
        await page.fill('#dummyName', 'Grid')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.locator('#dummyName').press('Space')
        assert.equal(await page.inputValue('#dummyName'), 'Grid ')
        assert.equal(await panScroll.evaluate(scroll => scroll.classList.contains('pan-ready')), false)
        await page.mouse.move(5, 5)
        const outsideSpace = await page.evaluate(() => {
            document.activeElement.blur()
            return document.body.dispatchEvent(new KeyboardEvent('keydown', { code: 'Space', bubbles: true, cancelable: true }))
        })
        assert.equal(outsideSpace, true, 'Space outside the canvas must keep its normal behavior')
        await page.fill('#dummyName', 'River Song')
        await page.evaluate(() => new Promise(requestAnimationFrame))
        await page.click('#fitZoom')
        await page.uncheck('#editPositions')
        assert.equal(await page.isDisabled('#snapSelected'), true)
        await checkWorkflow(browser, page.url(), screenshots)
        await checkFonts(browser, page.url(), screenshots)
        await checkResolutions(browser, screenshots)
        await checkMotion(browser, page.url())
        await checkCustomResolutions(browser, page.url(), screenshots)
        await checkHardening(browser, page.url())
        await page.setViewportSize({ width: 390, height: 844 })
        await page.click('#demoUI')
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('success'))
        await page.click('#viewOriginal')
        await page.screenshot({ path: path.join(screenshots, 'delvui-mobile.png'), fullPage: true })
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
        assert.deepEqual(errors, [])
        console.log(`Browser checks passed. Screenshots: ${screenshots}`)
    } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 }).finally(() => server.close())
