const assert = require('node:assert/strict')
const http = require('node:http')
const path = require('node:path')
const { createServer } = require('../../scripts/serve.cjs')

module.exports = async function checkResolutions(browser, screenshots) {
    const files = createServer()
    const server = http.createServer((request, response) => {
        if (!request.url.startsWith('/DelvUIScaler/')) { response.writeHead(404).end(); return }
        request.url = request.url.slice('/DelvUIScaler'.length)
        files.emit('request', request, response)
    })
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('response', response => { if (response.url().includes('127.0.0.1') && response.status() >= 400) errors.push(response.url()) })
    try {
        await page.goto(`http://127.0.0.1:${server.address().port}/DelvUIScaler/`, { waitUntil: 'networkidle' })
        await page.click('#demoUI')
        const selectPlayer = async () => {
            const id = await page.locator('#previewElement option').evaluateAll(options => options.find(option => option.text === 'Player Unit Frame').value)
            await page.selectOption('#previewElement', id)
            return page.locator(`[data-element=${JSON.stringify(id)}]`)
        }
        const exportProfile = async () => {
            await page.click('#processBtn')
            return page.evaluate(() => ConfigCodec.decode(document.getElementById('outputStr').value))
        }
        const viewport = () => page.locator('#previewSvg').evaluate(svg => {
            const { x, y, width, height } = svg.viewBox.baseVal
            return { x, y, width, height }
        })
        const rect = async element => element.locator('rect').first().evaluate(rect =>
            ({ x: Number(rect.getAttribute('x')), y: Number(rect.getAttribute('y')) }))
        const drag = async (element, dx, dy) => {
            const bounds = await element.boundingBox(), svg = await page.locator('#previewSvg').boundingBox(), world = await viewport()
            await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
            await page.mouse.down()
            await page.mouse.move(bounds.x + bounds.width / 2 + dx, bounds.y + bounds.height / 2 + dy, { steps: 5 })
            await page.mouse.up()
            return dx * world.width / svg.width
        }
        const before = await exportProfile()
        const output = await page.inputValue('#outputStr')
        await page.click('#viewOriginal')
        const originalRect = await rect(await selectPlayer())
        await page.check('#showResolutions')
        assert.equal(await page.inputValue('#outputStr'), output)
        assert.deepEqual(await viewport(), { x: -640, y: -360, width: 3840, height: 2160 })
        assert.deepEqual(await rect(await selectPlayer()), originalRect)
        assert.equal(await page.locator('[data-resolution]').count(), 3)
        assert.match(await page.textContent('#resolutionSizes'), /1080p · 1920 × 1080/)
        assert.match(await page.textContent('#resolutionSizes'), /1440p · 2560 × 1440/)
        assert.match(await page.textContent('#resolutionSizes'), /2160p \/ 4K · 3840 × 2160/)
        await page.locator('#screenScroll').screenshot({ path: path.join(screenshots, 'resolution-bounds.png') })
        await page.check('#editPositions')
        await page.uncheck('#smartGuides')
        let player = await selectPlayer()
        const delta = await drag(player, 20, 10)
        assert.ok(Math.abs(Number(await page.inputValue('#positionX')) - (-360 + delta)) < .1)
        await page.click('#undoEdit')
        assert.equal(await page.inputValue('#positionX'), '-360')
        await page.click('[data-align="left"]')
        assert.ok(Math.abs((await rect(await selectPlayer())).x) < .01, 'Screen alignment uses the real screen, not the expanded viewport')
        await page.click('#resetAllPositions')
        await page.fill('#gridX', '26')
        await page.check('#snapGrid')
        await page.fill('#positionX', '-355')
        await page.locator('#positionX').press('Tab')
        let world = await viewport(), corner = await rect(await selectPlayer())
        let units = (corner.x - (world.x + world.width / 2)) / 26
        assert.ok(Math.abs(units - Math.round(units)) < .001)
        assert.equal(await page.inputValue('#positionY'), '330')
        await page.click('#resetAllPositions')
        await page.click('#focusView')
        const focused = await (await selectPlayer()).boundingBox(), scroll = await page.locator('#screenScroll').boundingBox()
        assert.ok(Math.abs(focused.x + focused.width / 2 - (scroll.x + scroll.width / 2)) < 4)
        assert.ok(Math.abs(focused.y + focused.height / 2 - (scroll.y + scroll.height / 2)) < 4)
        await page.click('#fitZoom')
        assert.deepEqual(await exportProfile(), before)
        await page.selectOption('#targetRes', '1080')
        await page.click('#viewScaled')
        assert.deepEqual(await viewport(), { x: -960, y: -540, width: 3840, height: 2160 })
        await selectPlayer()
        assert.equal(await page.inputValue('#positionX'), '-270')
        await page.uncheck('#snapGrid')
        const scaledDelta = await drag(await selectPlayer(), 12, 5)
        assert.ok(Math.abs(Number(await page.inputValue('#positionX')) - (-270 + scaledDelta)) < .1)
        await page.click('#resetAllPositions')
        await page.check('#snapGrid')
        await page.click('#snapSelected')
        world = await viewport()
        corner = await rect(await selectPlayer())
        units = (corner.x - (world.x + world.width / 2)) / 26
        assert.ok(Math.abs(units - Math.round(units)) < .001)
        await page.click('#resetAllPositions')
        await page.selectOption('#aspectRatio', String(21 / 9))
        await page.click('#viewOriginal')
        assert.deepEqual(await viewport(), { x: -840, y: -360, width: 5040, height: 2160 })
        assert.match(await page.textContent('#resolutionSizes'), /1440p · 3360 × 1440/)
        await page.selectOption('#aspectRatio', String(32 / 9))
        assert.deepEqual(await viewport(), { x: -1280, y: -360, width: 7680, height: 2160 })
        assert.match(await page.textContent('#resolutionSizes'), /2160p \/ 4K · 7680 × 2160/)
        await page.selectOption('#aspectRatio', String(21 / 9))
        await page.uncheck('#showResolutions')
        assert.deepEqual(await viewport(), { x: 0, y: 0, width: 3360, height: 1440 })
        await page.check('#showResolutions')
        await page.reload({ waitUntil: 'networkidle' })
        assert.equal(await page.isChecked('#showResolutions'), true)
        assert.equal(await page.inputValue('#inputStr'), '')
        await page.setViewportSize({ width: 390, height: 844 })
        await page.click('#demoCD')
        await page.locator('#screenScroll').screenshot({ path: path.join(screenshots, 'resolution-bounds-mobile.png') })
        assert.equal(await page.locator('[data-resolution]').count(), 3)
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
        if (process.env.DELVUI_SAMPLE) {
            await page.setViewportSize({ width: 1440, height: 1000 })
            await page.setInputFiles('#profileFile', process.env.DELVUI_SAMPLE)
            await page.waitForFunction(() => document.getElementById('inputStatus').textContent.includes('91 sections'))
            const supplied = await exportProfile()
            await page.click('#viewOriginal')
            await page.uncheck('#showResolutions')
            await page.check('#showResolutions')
            assert.equal(await page.locator('[data-resolution]').count(), 3)
            assert.deepEqual(await exportProfile(), supplied)
            await page.click('#viewOriginal')
            await page.locator('#screenScroll').screenshot({ path: path.join(screenshots, 'resolution-bounds-profile.png') })
        }
        assert.deepEqual(errors, [])
        console.log('Resolution bounds, editing and GitHub Pages path checks passed.')
    } finally {
        await page.close()
        await new Promise(resolve => server.close(resolve))
    }
}
