const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

module.exports = async function checkWorkflow(browser, url, screenshots) {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    try {
        await page.goto(url, { waitUntil: 'networkidle' })
        await page.click('#demoUI')
        const input = await page.inputValue('#inputStr')
        await page.setInputFiles('#profileFile', { name: 'My layout.delvui', mimeType: 'text/plain', buffer: Buffer.from('\ufeff' + input) })
        await page.waitForFunction(() => document.getElementById('inputStatus').textContent.includes('sections'))
        assert.equal(await page.textContent('#profileKind'), 'DelvUI')
        assert.equal(await page.isDisabled('#undoEdit'), true)
        const selectPlayer = async () => {
            const id = await page.locator('#previewElement option').evaluateAll(options => options.find(option => option.text === 'Player Unit Frame').value)
            await page.selectOption('#previewElement', id)
            return page.locator(`[data-element=${JSON.stringify(id)}]`)
        }
        const canvas = page.locator('#screenScroll')
        const x = async () => Number(await page.inputValue('#positionX'))
        const y = async () => Number(await page.inputValue('#positionY'))
        await selectPlayer()
        await page.check('#editPositions')
        await page.uncheck('#smartGuides')
        await canvas.focus()
        await page.keyboard.press('ArrowRight')
        assert.equal(await x(), -359)
        await page.keyboard.press('Shift+ArrowDown')
        assert.equal(await y(), 340)
        await page.keyboard.press('Control+z')
        assert.equal(await y(), 330)
        await page.keyboard.press('Control+Shift+z')
        assert.equal(await y(), 340)
        await page.fill('#gridX', '32')
        await page.check('#snapGrid')
        await canvas.focus()
        await page.keyboard.press('ArrowRight')
        const gridUnits = await (await selectPlayer()).evaluate(group =>
            (Number(group.querySelector('rect').getAttribute('x')) - group.ownerSVGElement.viewBox.baseVal.width / 2) / 32)
        assert.notEqual(await x(), -359)
        assert.equal(await y(), 340)
        assert.ok(Math.abs(gridUnits - Math.round(gridUnits)) < .001, 'Arrow movement snaps the rendered corner')
        await page.click('#undoEdit')
        assert.equal(await x(), -359)
        await page.selectOption('#moveAxis', 'x')
        await canvas.focus()
        await page.keyboard.press('ArrowUp')
        assert.equal(await y(), 340)
        assert.equal(await x(), -359, 'A locked arrow must not snap the other axis')
        await page.uncheck('#snapGrid')
        await page.selectOption('#moveAxis', 'free')
        await page.fill('#dummyName', 'Arrow test')
        await page.keyboard.press('ArrowRight')
        assert.equal(await x(), -359)
        await page.click('#resetAllPositions')
        await page.click('#undoEdit')
        assert.equal(await x(), -359)
        assert.equal(await y(), 340)
        await page.click('#redoEdit')
        assert.equal(await x(), -360)
        assert.equal(await y(), 330)
        await page.fill('#manualScale', '2')
        await page.locator('#manualScale').press('Tab')
        await page.click('#viewScaled')
        assert.equal(await x(), -720)
        await canvas.focus()
        await page.keyboard.press('ArrowRight')
        assert.equal(await x(), -719)
        await page.click('#undoEdit')
        assert.equal(await x(), -720)
        await page.click('#undoEdit')
        assert.equal(await page.inputValue('#manualScale'), '1.500')
        assert.equal(await x(), -540)
        await page.click('#redoEdit')
        assert.equal(await page.inputValue('#manualScale'), '2')
        await page.selectOption('#targetRes', '1080')
        assert.equal(await page.inputValue('#manualScale'), '0.750')
        await page.click('#undoEdit')
        assert.equal(await page.inputValue('#targetRes'), '2160')
        assert.equal(await page.inputValue('#manualScale'), '2')
        await page.click('#viewOriginal')
        const player = await selectPlayer(), box = await player.boundingBox()
        await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
        await page.mouse.down()
        await page.mouse.move(box.x + box.width / 2 + 35, box.y + box.height / 2 - 10, { steps: 12 })
        await page.mouse.up()
        const moved = await x()
        assert.notEqual(moved, -360)
        await page.click('#undoEdit')
        assert.equal(await x(), -360, 'One undo restores a whole drag')
        await page.click('#redoEdit')
        assert.equal(await x(), moved)
        await page.click('[data-align="centerX"]')
        const centered = await x()
        assert.notEqual(centered, moved)
        await page.click('#undoEdit')
        assert.equal(await x(), moved)
        await page.click('#processBtn')
        const output = await page.inputValue('#outputStr')
        const downloadEvent = page.waitForEvent('download')
        await page.click('#downloadBtn')
        const download = await downloadEvent
        assert.equal(download.suggestedFilename(), 'My layout-scaled.delvui')
        assert.equal(fs.readFileSync(await download.path(), 'utf8'), output)
        await page.setInputFiles('#profileFile', { name: 'bad.txt', mimeType: 'text/plain', buffer: Buffer.from('bad profile') })
        await page.waitForFunction(() => document.getElementById('inputStatus').classList.contains('error'))
        assert.equal(await page.textContent('#profileKind'), 'No profile loaded')
        assert.equal(await page.isDisabled('#downloadBtn'), true)
        assert.equal(await page.isDisabled('#undoEdit'), true)
        const cd = await page.evaluate(() => ConfigCodec.encode(DemoProfiles.DelvCD))
        await page.locator('#profileDrop').evaluate((drop, text) => {
            const transfer = new DataTransfer()
            transfer.items.add(new File([text], 'cooldowns.txt', { type: 'text/plain' }))
            drop.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: transfer }))
        }, cd)
        await page.waitForFunction(() => document.getElementById('profileKind').textContent === 'DelvCD')
        await page.click('#processBtn')
        assert.equal(await page.isDisabled('#downloadBtn'), false)
        await page.evaluate(() => {
            window.originalFileText = File.prototype.text
            File.prototype.text = function () { return new Promise(resolve => { window.finishFileRead = resolve }) }
        })
        await page.setInputFiles('#profileFile', { name: 'slow.delvui', mimeType: 'text/plain', buffer: Buffer.from(input) })
        await page.waitForFunction(() => typeof window.finishFileRead === 'function')
        assert.equal(await page.isDisabled('#downloadBtn'), true, 'Opening a new file invalidates the old export immediately')
        assert.equal(await page.inputValue('#outputStr'), '')
        await page.click('#processBtn')
        assert.equal(await page.inputValue('#outputStr'), '', 'Cannot regenerate the previous profile during a file read')
        await page.click('#clearBtn')
        await page.evaluate(text => { window.finishFileRead(text); File.prototype.text = window.originalFileText }, input)
        assert.equal(await page.inputValue('#inputStr'), '')
        assert.equal(await page.textContent('#profileKind'), 'No profile loaded')
        await page.click('#demoUI')
        await page.click('#processBtn')
        await page.evaluate(() => { File.prototype.text = () => Promise.reject(new Error('read failure')) })
        await page.setInputFiles('#profileFile', { name: 'unreadable.txt', mimeType: 'text/plain', buffer: Buffer.from(input) })
        await page.waitForFunction(() => document.getElementById('inputStatus').textContent === 'Could not read this file.')
        assert.equal(await page.inputValue('#outputStr'), '')
        assert.equal(await page.isDisabled('#downloadBtn'), true)
        await page.evaluate(() => { File.prototype.text = window.originalFileText })
        await page.fill('#gridX', '32')
        await page.fill('#gridY', '48')
        await page.check('#snapGrid')
        await page.selectOption('#moveAxis', 'y')
        await page.selectOption('#focusMode', 'dim')
        await page.locator('#previewZoom').evaluate(slider => { slider.value = '250'; slider.dispatchEvent(new Event('input', { bubbles: true })) })
        const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('delvuiscaler.preview.v1')))
        assert.equal(Object.hasOwn(saved, 'inputStr'), false)
        await page.reload({ waitUntil: 'networkidle' })
        assert.equal(await page.inputValue('#gridX'), '32')
        assert.equal(await page.inputValue('#gridY'), '48')
        assert.equal(await page.inputValue('#previewZoom'), '250')
        assert.equal(await page.inputValue('#moveAxis'), 'y')
        assert.equal(await page.inputValue('#focusMode'), 'dim')
        assert.equal(await page.isChecked('#snapGrid'), true)
        assert.equal(await page.isChecked('#editPositions'), false)
        assert.equal(await page.inputValue('#inputStr'), '')
        await page.evaluate(() => localStorage.setItem('delvuiscaler.preview.v1', '{broken'))
        await page.reload({ waitUntil: 'networkidle' })
        assert.equal(await page.inputValue('#gridX'), '20')
        assert.equal(await page.inputValue('#previewZoom'), '100')
        await page.addInitScript(() => {
            Storage.prototype.getItem = () => { throw new Error('Storage blocked') }
            Storage.prototype.setItem = () => { throw new Error('Storage blocked') }
        })
        await page.reload({ waitUntil: 'networkidle' })
        await page.fill('#gridY', '30')
        await page.click('#demoUI')
        await selectPlayer()
        await page.check('#editPositions')
        await page.screenshot({ path: path.join(screenshots, 'editing-sidebar.png'), fullPage: true })
        const canvasBox = await canvas.boundingBox(), align = await page.locator('.alignment-buttons').boundingBox()
        assert.ok(align.x > canvasBox.x + canvasBox.width, 'Alignment sits beside the canvas')
        assert.ok(align.y < canvasBox.y + canvasBox.height + 180, 'Alignment stays close to the canvas')
        await page.setViewportSize({ width: 390, height: 844 })
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
        assert.deepEqual(errors, [])
        console.log('History, keyboard, files and saved settings checks passed.')
    } finally { await page.close() }
}
