const test = require('node:test')
const assert = require('node:assert/strict')
const { ProfileEditor } = require('../../src/profile/editor.js')

const path = ['configs', 0, 'Position']
const other = ['configs', 1, 'Position']
const settings = { baseRes: '2560x1440', targetRes: '1920x1080', manualScale: '' }
function create() {
    return new ProfileEditor({ configs: [{ Position: { X: 10, Y: 20, $type: 'Vector2', Extra: { kept: true } } }, {}] }, settings)
}

test('settings and positions undo and redo in one ordered history without mutating inputs', () => {
    const editor = create(), next = { ...settings, manualScale: '1.5' }
    editor.setPosition(path, 30, 40)
    editor.setSettings(next)
    next.manualScale = '999'
    editor.setPosition(path, 50, 60)
    assert.equal(editor.undo(), true)
    assert.deepEqual(editor.position(path), { X: 30, Y: 40 })
    assert.equal(editor.settings.manualScale, '1.5')
    assert.equal(editor.undo(), true)
    assert.deepEqual(editor.settings, settings)
    assert.equal(editor.changed.size, 1)
    assert.equal(editor.undo(), true)
    assert.deepEqual(editor.working, editor.original)
    assert.equal(editor.changed.size, 0)
    assert.equal(editor.undo(), false)
    assert.equal(editor.canUndo, false)
    assert.equal(editor.canRedo, true)
    for (let i = 0; i < 3; i++) assert.equal(editor.redo(), true)
    assert.deepEqual(editor.position(path), { X: 50, Y: 60 })
    assert.equal(editor.settings.manualScale, '1.5')
    assert.equal(editor.redo(), false)
    assert.deepEqual(settings, { baseRes: '2560x1440', targetRes: '1920x1080', manualScale: '' })
})

test('pointer drag coalesces many changes to one sparse command', () => {
    const editor = create()
    editor.beginTransaction()
    for (let i = 0; i < 5000; i++) editor.setPosition(path, i, i + 1)
    assert.equal(editor.undoStack.length, 0)
    assert.equal(editor.transaction.positions.size, 1)
    assert.equal(editor.endTransaction(), true)
    assert.equal(editor.undoStack.length, 1)
    assert.equal(editor.undoStack[0].positions.length, 1)
    assert.equal(Object.hasOwn(editor.undoStack[0], 'working'), false)
    editor.undo()
    assert.deepEqual(editor.working, editor.original)
    editor.redo()
    assert.deepEqual(editor.position(path), { X: 4999, Y: 5000 })
})

test('reset and resetAll can restore edits with exact metadata and missing properties', () => {
    const editor = create()
    editor.setPosition(path, 33, 44)
    editor.setPosition(other, 55, 66)
    const edited = structuredClone(editor.working)
    assert.equal(editor.resetAll(), true)
    assert.deepEqual(editor.working, editor.original)
    assert.equal(editor.changed.size, 0)
    assert.equal(editor.undo(), true)
    assert.deepEqual(editor.working, edited)
    assert.equal(editor.changed.size, 2)
    assert.equal(editor.redo(), true)
    assert.equal(Object.hasOwn(editor.working.configs[1], 'Position'), false)
    editor.undo()
    editor.reset(path)
    assert.deepEqual(editor.working.configs[0], editor.original.configs[0])
    editor.undo()
    assert.deepEqual(editor.working, edited)
    editor.undo()
    assert.equal(Object.hasOwn(editor.working.configs[1], 'Position'), false)
    assert.equal(editor.changed.size, 1)
})

test('undo preserves explicit undefined position and redo creates the moved vector', () => {
    const editor = new ProfileEditor({ configs: [{ Position: undefined }] })
    editor.setPosition(path, 1, 2)
    editor.undo()
    assert.equal(Object.hasOwn(editor.working.configs[0], 'Position'), true)
    assert.equal(editor.working.configs[0].Position, undefined)
    editor.redo()
    assert.deepEqual(editor.working.configs[0].Position, { X: 1, Y: 2 })
})

test('new actions discard redo while invalid, locked and net-zero actions keep it', () => {
    const editor = create()
    editor.setPosition(path, 33, 44)
    editor.undo()
    assert.equal(editor.setPosition(path, 10, 99, 'x'), false)
    assert.equal(editor.setPosition(path, 99, 20, 'y'), false)
    assert.equal(editor.setPosition(path, NaN, 20), false)
    assert.equal(editor.setPosition(['missing', 'Position'], 1, 2), false)
    assert.equal(editor.setPosition([], 1, 2), false)
    assert.equal(editor.reset(path), false)
    assert.equal(editor.resetAll(), false)
    assert.equal(editor.setSettings({ manualScale: '', targetRes: settings.targetRes, baseRes: settings.baseRes }), false)
    editor.beginTransaction()
    editor.setPosition(path, 100, 200)
    editor.setPosition(path, 10, 20)
    assert.equal(editor.endTransaction(), false)
    assert.equal(editor.canRedo, true)
    editor.redo()
    assert.deepEqual(editor.position(path), { X: 33, Y: 44 })
    editor.undo()
    editor.setSettings({ ...settings, targetRes: '3840x2160' })
    assert.equal(editor.canRedo, false)
    assert.equal(editor.redo(), false)
})

test('transactions preserve axis locks and combine multiple position owners', () => {
    const editor = create()
    editor.beginTransaction()
    editor.setPosition(path, 30, 999, 'x')
    editor.setPosition(other, 40, 50)
    editor.setPosition(path, 999, 60, 'y')
    editor.endTransaction()
    assert.deepEqual(editor.position(path), { X: 30, Y: 60 })
    editor.undo()
    assert.deepEqual(editor.working, editor.original)
    editor.redo()
    assert.deepEqual(editor.position(path), { X: 30, Y: 60 })
    assert.deepEqual(editor.position(other), { X: 40, Y: 50 })
})

test('history retains the last 100 commands and replays them consistently', () => {
    const editor = create()
    for (let i = 1; i <= 125; i++) editor.setPosition(path, 10 + i, 20)
    assert.equal(editor.undoStack.length, 100)
    for (let i = 0; i < 100; i++) assert.equal(editor.undo(), true)
    assert.equal(editor.undo(), false)
    assert.deepEqual(editor.position(path), { X: 35, Y: 20 })
    assert.equal(editor.changed.size, 1)
    for (let i = 0; i < 100; i++) assert.equal(editor.redo(), true)
    assert.equal(editor.redo(), false)
    assert.deepEqual(editor.position(path), { X: 135, Y: 20 })
})

test('nested transactions group settings and position edits and undo closes an active drag', () => {
    const editor = create()
    editor.beginTransaction()
    editor.setPosition(path, 30, 40)
    editor.beginTransaction()
    editor.setSettings({ ...settings, manualScale: '2' })
    assert.equal(editor.endTransaction(), false)
    assert.equal(editor.undo(), true)
    assert.equal(editor.transactionDepth, 0)
    assert.deepEqual(editor.working, editor.original)
    assert.deepEqual(editor.settings, settings)
    editor.redo()
    assert.deepEqual(editor.position(path), { X: 30, Y: 40 })
    assert.equal(editor.settings.manualScale, '2')
})
